# https://www.appveyor.com/docs/windows-images-software

image: Visual Studio 2022

environment:
  global:
    REPO_DIR: python-appveyor-demo
    PACKAGE_NAME: python_appveyor_demo
    BUILD_COMMIT: master
    BUILD_DEPENDS: "cython"
    TEST_DEPENDS: "nose"

  matrix:
    - PYTHON: "C:\\Miniconda37"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Miniconda37-x64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Miniconda38-x64"
      PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "64"

# We always use a 64-bit machine, but can build x86 distributions
# with the TARGET_ARCH variable.
platform:
    - x64

matrix:
    fast_finish: false

install:
    # Install miniconda and fix headers
    - where python
    - where py  # On Windows, py might be a better way to find and run CPython
    - py --list  # py -3.10-32, -3.10-64 with same syntax for 3.{9-3}, 2.{7,6}
    - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PYTHON%\Library\bin;%PATH%
    - echo %PATH%
    - where conda
    - conda info

    # Check that we have the expected version and architecture for Python
    - python --version
    - python -c "import struct; print(struct.calcsize('P') * 8)"
    - py --version
    - py -c "import struct; print(struct.calcsize('P') * 8)"

    # clone a origsel/python-appveyor-demo
    # this repo includes a simple package to test appveyor
    - git clone https://github.com/ogrisel/python-appveyor-demo.git

build_script:
    # Install build requirements
    - conda install --yes %BUILD_DEPENDS%

    # build wheel:
    - cd %REPO_DIR%
    - git checkout %BUILD_COMMIT%
    - python setup.py bdist_wheel
    - ls dist/*

test_script:
    # create test env
    - conda create --yes -n test_env python=%PYTHON_VERSION% %TEST_DEPENDS%
    - activate test_env

    # install from wheel
    - pip install --no-index --find-links dist/ %PACKAGE_NAME%

    # run tests from install wheel
    - cd ..
    - python -m pyappveyordemo.tests.test_extension

    # Smoke test of install_python script
    # Use C:\PythonXY, C:\PythonXY-x64, C:\PythonXYrcZ, or C:\PythonXYrcZ-x64
    - set PYTHON=C:\Python37
    - ps: .\install_python.ps1
    - set PYTHON=C:\Python37-x64
    - ps: .\install_python.ps1
    - set PYTHON=C:\Python38-x64
    - ps: .\install_python.ps1
    - set PYTHON=C:\Python38
    - ps: .\install_python.ps1
    - set PYTHON=C:\Python39-x64
    - ps: .\install_python.ps1
    - set PYTHON=C:\Python39
    - ps: .\install_python.ps1
    - set PYTHON=C:\Python310-x64
    - ps: .\install_python.ps1
    - set PYTHON=C:\Python310
    - ps: .\install_python.ps1
