# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the devel branch
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-latest ] #, windows-latest]
        python-version: ["3.13"]  # ["2.7", "3.7", "3.8", "3.9", "3.10", "3.11", "3.12", "pypy3"]

        include:
          # By default, specify an OSX_VER of 11.0, triggering ARM64 build.
          - python-osx-ver: "11.0"

          # macos-13 is the last remaining x86-64 runner;
          # set OSX_VER to 10.9 trigger x86_64 builds by default.
          - os: macos-13
            python-osx-ver: "10.9"

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    env:
      MB_PYTHON_VERSION: 3.13
      TEST_BUILDS: 1
      MB_PYTHON_OSX_VER: ${{ matrix.python-osx-ver }}
      ENV_VARS_PATH: "test/env_vars.sh"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Runs a single command using the runner's Python
      - name: Test
        run: |
          pip install setuptools  # for distutils
          source tests/test_multibuild.sh
